name := "Simple Project"
version := "1.0"
scalaVersion := "2.10.4"
libraryDependencies += "org.apache.spark" % "spark-core_2.10" % "2.0.0"
libraryDependencies += "org.apache.spark" % "spark-sql_2.10" % "2.0.0"
libraryDependencies += "org.apache.spark" % "spark-hive_2.10" % "2.0.0"